[Lab1] Create website
Evelissia/effective-web-course pull request #1
Opened 2022-11-03 21:16 UTC by Evelissia

Polovtseva Viktoria

2022-11-04 18:53 UTC, konstantinzelinsky commented
Привет! Над адаптивной версткой надо еще работать
<img width="503" alt="image" src="https://user-images.githubusercontent.com/57330800/200052437-179f1a3c-2ad4-44df-affd-7e28109b9166.png">

Также необходимо исправить несколько ошибок валидатора.

После исправления ошибок готов поставить 12 баллов (если не править адаптив)

Также еще есть проблема в названии ветки - должно быть `feature/lab1_htm_css`. Но в первой лабе прощаю)

2022-11-04 18:56 UTC, konstantinzelinsky requested changes
Поправить валидатор
Опционально - поправить адаптив

2022-11-04 20:40 UTC, merged

2022-11-04 20:41 UTC, Evelissia commented
Исправила ошибки

2022-11-05 07:30 UTC, konstantinzelinsky commented
<img width="509" alt="image" src="https://user-images.githubusercontent.com/57330800/200108339-8cf01f7e-3537-4f12-bcef-0b2210d8a5bb.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/57330800/200108358-14f7e52b-1a0a-4b74-9f88-dd2d7f5f1c9c.png">
Адаптивная верстка едет

Принял, 12 баллов